apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/node-feature-discovery-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard

patches:
- target:
    kind: ClusterServiceVersion
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        operators.openshift.io/infrastructure-features: '["disconnected"]'
        
